version: '3'
services:
  app:
    build: .
    command: yarn run dev
    volumes:
      - .:/app
    ports:
      - '${SERVER_PORT:-3300}:${SERVER_PORT:-3300}'
    networks: 
      - app
      
networks:
  app:
    driver: bridge