version: 2.1
jobs:
  specs:
    working_directory: ~/micro-express/specification
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout:
          path: ~/micro-express
      - node/install:
          install-npm: false
          node-version: latest
      - run: node ./test-apis.js
      - run: node ./test-events.js
      - slack/status:
          fail_only: true
          webhook: $SLACK_WEBHOOK
  services:
    working_directory: ~/micro-express/services
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout:
          path: ~/micro-express
      - setup_remote_docker
      - run: ./launcher.sh -e test
      - slack/status:
          fail_only: true
          webhook: $SLACK_WEBHOOK
orbs:
  node: circleci/node@2.0.3
  slack: circleci/slack@3.4.2
workflows:
  micro-express:
    jobs:
      - specs:
          filters:
            branches:
              only:
                - master
                - staging
                - dev
      - services:
          filters:
            branches:
              only:
                - master
                - staging
                - dev
