version: '3'
services:
  app:
    build: .
    command: sh -c "./wait-for-it.sh -t 15 prisma:4466 --strict -- prisma deploy && yarn run ${ENV:-dev}"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    networks: 
      - api-gateway_krakend
      - app
    depends_on:
      - prisma
    environment:
      PRISMA_MANAGEMENT_API_SECRET: ${PRISMA_MANAGEMENT_API_SECRET:-wsflk897dh%£}

  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    networks: 
      - app
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET:-wsflk897dh%£}
        databases:
          default:
            connector: postgres
            host: ${DB_HOST}
            port: ${DB_PORT}
            database: ${DB_NAME}
            schema: public
            user: ${DB_USER}
            password: ${DB_PASSWORD}
      
networks:
  api-gateway_krakend:
    external: true
  app:
    driver: bridge